Revert ":cut: remove unnecessary rescue Exceptions"
This reverts commit ff18049ca6f27deb7e7f955478e1464f8d756332.

This broke the AR build for every adapter:

      1) Error:
    AssociationCallbacksTest#test_dont_add_if_before_callback_raises_exception:
    Exception: You can't add a post

      2) Failure:
    QueryCacheTest#test_query_cache_doesnt_leak_cached_results_of_rolled_back_queries [/Users/senny/Projects/rails/activerecord/test/cases/query_cache_test.rb:235]:
    Expected: 1
      Actual: 0

I'm reverting to get the build green again.