[ci skip] add `controller:` argument to routing.md
Passing a `Symbol` to the `to:` argument for a `get` route requires a `controller` argument to also be defined.
The documentation is missing the `controller:` argument, which leaving out raises a routing exception:

```ruby
get 'profile', to: :show
```

```
$ rake routes
ArgumentError: Missing :controller key on routes definition, please check your routes.
```

Adding the `controller:` argument maps the route correctly:

```ruby
get 'profile', to: :show, controller: 'users'
```
```
$ rake routes
profile GET    /profile(.:format)  users#show
```