`require "active_support/test_case"` is not supported since 53e877f7
It will cause "undefined method `test_order' for ActiveSupport:Module
(NoMethodError)".

https://travis-ci.org/rails/rails/jobs/373472604#L1208