require 'rake' before requiring Rake tasks
Without this,
% rails r "require 'rails/tasks'"
would cause a NoMethodError: undefined method `desc' for main:Object