update test_help to config properly turn natural language option
Last versions of Turn don't monkey patch MiniTest to setup
the natural language option. Here is an
[example](https://github.com/TwP/turn/blob/master/try/test_autorun_minitest.rb#L3).

This patches the following behaviour:

    $ rake test:units
    `<top (required)>': undefined method `use_natural_language_case_names='
    for MiniTest::Unit:Class (NoMethodError)