Fix guide generation error [ci skip]
Currently, generation of guide is an error in `5_2_release_notes.html`.

```
$ bunele exec rake guides:generate:html
Generating 5_2_release_notes.md as 5_2_release_notes.html
rails/guides/rails_guides/markdown.rb:44:in `dom_id': undefined method `[]' for nil:NilClass (NoMethodError)
	from rails/guides/rails_guides/markdown.rb:106:in `block (2 levels) in generate_structure'
```

It seems that it is an error because there are multiple
`active-storage` anchors.

Since Active Storage is a Major feature, it is unnecessary to show
CHANGELOGs, so remove from `Incompatibilities` section.